### ISSUE TITLE
Pytorch version >= 1.13

### ISSUE THREAD

**Issue by HMRLKE** [juditacs/probing#1]
When installing this library to an environment which uses `pytorch 1.12.1`, everything works fine. Once the Pytorch version is greater than `1.13`, dict subscription problems arise. I suspect, that it has something to do with this modification: https://github.com/pytorch/pytorch/issues/72778. Usage with downgraded `pytorch` can still be an option, however the README recommends installing PyTorch before the `probing` package without mentioning any kind of upper-bound regarding the version of the `pytorch`.

The first error I get when trying to use `probing` with `pytorch >= 1.13` is an IndexError:

`
Traceback (most recent call last):
  File "~/probing/src/probing/train.py", line 38, in <module>
    main()
  File "~/probing/src/probing/train.py", line 32, in main
    e.run()
  File "~/probing/src/probing/experiment.py", line 152, in run
    self.model.run_train(
  File "~/probing/src/probing/models/base.py", line 60, in run_train
    s = self.save_if_best(result, epoch)
  File "~/probing/src/probing/models/base.py", line 154, in save_if_best
    self._save(epoch)
  File "~/probing/src/probing/models/base.py", line 174, in _save
    torch.save(self.state_dict(), save_path)
  File "~/miniconda3/envs/dep-probe/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1444, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "~/probing/src/probing/models/contextual_embedding_classifier.py", line 135, in state_dict
    return args[0]
IndexError: tuple index out of range
`

**Comment by juditacs** [comment]
Yes, the signature of `state_dict` was changed. I added a fix and it now supports both the old and the new version.

Fixed with https://github.com/juditacs/probing/commit/860acc00a75a287c1012ec6851216713a6d8d26e
